---
- name: Harden all nodes
  hosts: all
  gather_facts: yes
  roles:
    - hardening

- name: Install k3s server on master
  hosts: master
  gather_facts: yes
  roles:
    - k3s-server

- name: Install k3s agent on workers
  hosts: workers
  gather_facts: yes
  roles:
    - k3s-agent